class cloud extends entity{
    constructor(layer){
        super(layer,random(-80,980),random(-80,280),0,0)
        this.speed=random(1,1.5)
    }
    display(){
        this.layer.fill(255,this.fade)
        this.layer.stroke(245,this.fade)
        this.layer.strokeWeight(10)
        this.layer.ellipse(this.position.x,this.position.y,160,60)
    }
    update(){
        this.position.x+=this.speed
        if(this.position.x>980){
            this.position.x-=1060
            this.position.y-random(-80,630)
            this.speed=random(1,1.5)
        }
        super.update()
    }
}